### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by leolorenzoluis** [Nhowka/Elmish.Bridge#46]
I receive the following error when I push a lot of messages in multiple threads. Any guidance what it could mean? It works fine for few background threads and then it dies

```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Elmish.RingBuffer`1.Pop()
   at Elmish.ProgramModule.dispatch@140.Invoke(msg msg)
   at Elmish.Cmd.OfAsyncWith.bind@131-16.Invoke(msg _arg1)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, b result1, FSharpFunc`2 userCode) in D:\a\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 465
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\a\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 104
--- End of stack trace from previous location ---
   at Microsoft.FSharp.Control.AsyncPrimitives.Start@1078-1.Invoke(ExceptionDispatchInfo edi) in D:\a\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 1078
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\a\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 104
   at <StartupCode$FSharp-Core>.$Async.clo@181-16.Invoke(Object o) in D:\a\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 183
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
```

**Comment by Alkasai** [comment]
Same

**Comment by Nhowka** [comment]
I'm thinking that the Elmish ring buffer is not friendly when using multiple threads. I'll check the issues with it and probably revert it to using a MailboxProcessor again.

**Comment by Alkasai** [comment]
Do you know when you are planning to do this? Do you need any help?
I'm not familiar with the code-base, but who knows maybe I can help with anything.

**Comment by Nhowka** [comment]
A minimal repro code for the issue would be excellent. I tried to look at it earlier today, but only the stack trace didn't give me much information to understand the problem's root cause.

**Comment by Alkasai** [comment]
For sure.
- I start one client subscribes, which receives tons of messages (10s of messages per second) from the server.
- The messages from the server are sent using `hub.SendClientIf(fun client -> client.id = id)`
- I wait for a few minutes and everything is working fine.
- Next I start a second client, which also receives messages from server using `hub.SendClientIf(fun client -> client.id = id)`
- After a few minutes `hub.SendClientIf(fun client -> client.id = id)` throws exception:
```Exception thrown: 'System.NullReferenceException' in Elmish.dll
System.NullReferenceException: Object reference not set to an instance of an object.
   at Elmish.RingBuffer`1.Pop()
   at Elmish.ProgramModule.dispatch@140.Invoke(msg msg)
   at Microsoft.FSharp.Core.OptionModule.Iterate[T](FSharpFunc`2 action, FSharpOption`1 option) in D:\a\_work\1\s\src\fsharp\FSharp.Core\option.fs:line 50
   at Server.broadcastToSubscribers@23-1.Invoke(a arg10)
   at Server.subscriberClientMsgFn(SubscriberId sId, ServerToClientMessage yieldedMsg) in C:\Users\.....\Server.fs:line 30```

**Comment by Nhowka** [comment]
I'm uploading version 6.0.3, which uses a MailboxProcessor to control the access to the Elmish dispatcher, hopefully fixing the problem with multi-threading.

**Comment by Alkasai** [comment]
Thank you! Will give it a try.

**Comment by Alkasai** [comment]
Seems to be working. Thank you again, for the prompt fix!
